title: George (Yorgos) Stergiopoulos
description: [Assistant Professor of IT/OT Systems Security at the University of the Aegean, Greece | Security and Data Privacy Consultant]
logo: /pic.jpg
theme: jekyll-theme-minimal
